name: Push Tag

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: The tag to push
        required: true
        type: string

jobs:
  push-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Configure Git
        env:
          TOKEN: ${{ secrets.ACTIONS_GH_TOKEN }}
        run: |
          git config user.name "Release Bot"
          git config user.email "release-bot@users.noreply.github.com"
          git remote set-url origin "https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git"

      - name: Create and push tag
        run: |
          TAG_NAME="${{ github.event.inputs.tag_name }}"
          git tag "$TAG_NAME"
          git push origin "$TAG_NAME"
